
python3 run_sims.py config/contact_tracing_delay.yaml fall_realistic_updated_age_severity contact_tracing_delay_fall_realistic_updated_age_severity &
python3 run_sims.py config/contact_tracing_delay.yaml fall_realistic_updated_age_severity_testing contact_tracing_delay_fall_realistic_updated_age_severity_testing &


python3 run_sims.py config/contact_tracing_isolations.yaml fall_realistic_updated_age_severity contact_tracing_isolations_fall_realistic_updated_age_severity &
python3 run_sims.py config/contact_tracing_isolations.yaml fall_realistic_updated_age_severity_testing contact_tracing_isolations_fall_realistic_updated_age_severity_testing &


python3 run_sims.py config/testing/testing_qfnr.yaml fall_realistic_updated_age_severity_testing testing_qfnr_fall_realistic_updated_age_severity_testing &


