python run_sims.py config/contact_tracing_delay.yaml june_realistic contact_delay_june_realistic &
python run_sims.py config/contact_tracing_recall.yaml june_realistic contact_recall_june_realistic &
python run_sims.py config/daily_contacts.yaml june_realistic daily_contacts_june_realistic &
python run_sims.py config/exposed_infection_p.yaml june_realistic exposed_infection_p_june_realistic &
python run_sims.py config/mild_self_reporting.yaml june_realistic mild_self_reporting_june_realistic &
python run_sims.py config/prevalence.yaml june_realistic prevalence_june_realistic &
python run_sims.py config/severe_self_reporting.yaml june_realistic severe_self_reporting_june_realistic &

python run_sims.py config/contact_tracing_delay.yaml june_realistic_testing contact_delay_june_realistic_testing &
python run_sims.py config/contact_tracing_recall.yaml june_realistic_testing contact_recall_june_realistic_testing &
python run_sims.py config/daily_contacts.yaml june_realistic_testing daily_contacts_june_realistic_testing &
python run_sims.py config/exposed_infection_p.yaml june_realistic_testing exposed_infection_p_june_realistic_testing &
python run_sims.py config/mild_self_reporting.yaml june_realistic_testing mild_self_reporting_june_realistic_testing &
python run_sims.py config/prevalence.yaml june_realistic_testing prevalence_june_realistic_testing &
python run_sims.py config/severe_self_reporting.yaml june_realistic_testing severe_self_reporting_june_realistic_testing &

python run_sims.py config/contact_tracing_delay.yaml june_slightly_optimistic contact_delay_june_slightly_optimistic &
python run_sims.py config/contact_tracing_recall.yaml june_slightly_optimistic contact_recall_june_slightly_optimistic &
python run_sims.py config/daily_contacts.yaml june_slightly_optimistic daily_contacts_june_slightly_optimistic &
python run_sims.py config/exposed_infection_p.yaml june_slightly_optimistic exposed_infection_p_june_slightly_optimistic &
python run_sims.py config/mild_self_reporting.yaml june_slightly_optimistic mild_self_reporting_june_slightly_optimistic &
python run_sims.py config/prevalence.yaml june_slightly_optimistic prevalence_june_slightly_optimistic &
python run_sims.py config/severe_self_reporting.yaml june_slightly_optimistic severe_self_reporting_june_slightly_optimistic &

python run_sims.py config/contact_tracing_delay.yaml june_slightly_optimistic_testing contact_delay_june_slightly_optimistic_testing &
python run_sims.py config/contact_tracing_recall.yaml june_slightly_optimistic_testing contact_recall_june_slightly_optimistic_testing &
python run_sims.py config/daily_contacts.yaml june_slightly_optimistic_testing daily_contacts_june_slightly_optimistic_testing &
python run_sims.py config/exposed_infection_p.yaml june_slightly_optimistic_testing exposed_infection_p_june_slightly_optimistic_testing &
python run_sims.py config/mild_self_reporting.yaml june_slightly_optimistic_testing mild_self_reporting_june_slightly_optimistic_testing &
python run_sims.py config/prevalence.yaml june_slightly_optimistic_testing prevalence_june_slightly_optimistic_testing &
python run_sims.py config/severe_self_reporting.yaml june_slightly_optimistic_testing severe_self_reporting_june_slightly_optimistic_testing &

python run_sims.py config/contact_tracing_delay.yaml june_slightly_pessimistic contact_delay_june_slightly_pessimistic &
python run_sims.py config/contact_tracing_recall.yaml june_slightly_pessimistic contact_recall_june_slightly_pessimistic &
python run_sims.py config/daily_contacts.yaml june_slightly_pessimistic daily_contacts_june_slightly_pessimistic &
python run_sims.py config/exposed_infection_p.yaml june_slightly_pessimistic exposed_infection_p_june_slightly_pessimistic &
python run_sims.py config/mild_self_reporting.yaml june_slightly_pessimistic mild_self_reporting_june_slightly_pessimistic &
python run_sims.py config/prevalence.yaml june_slightly_pessimistic prevalence_june_slightly_pessimistic &
python run_sims.py config/severe_self_reporting.yaml june_slightly_pessimistic severe_self_reporting_june_slightly_pessimistic &

python run_sims.py config/contact_tracing_delay.yaml june_slightly_pessimistic_testing contact_delay_june_slightly_pessimistic_testing &
python run_sims.py config/contact_tracing_recall.yaml june_slightly_pessimistic_testing contact_recall_june_slightly_pessimistic_testing &
python run_sims.py config/daily_contacts.yaml june_slightly_pessimistic_testing daily_contacts_june_slightly_pessimistic_testing &
python run_sims.py config/exposed_infection_p.yaml june_slightly_pessimistic_testing exposed_infection_p_june_slightly_pessimistic_testing &
python run_sims.py config/mild_self_reporting.yaml june_slightly_pessimistic_testing mild_self_reporting_june_slightly_pessimistic_testing &
python run_sims.py config/prevalence.yaml june_slightly_pessimistic_testing prevalence_june_slightly_pessimistic_testing &
python run_sims.py config/severe_self_reporting.yaml june_slightly_pessimistic_testing severe_self_reporting_june_slightly_pessimistic_testing &

